POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Jake",
  "number": "012-345-6789"
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "",
  "number": "012-345-6789"
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Jane",
  "number": ""
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Fe",
  "number": "44"
}