POST https://immense-brushlands-16614.herokuapp.com/api/persons/
Content-Type: application/json

{
  "name": "Jake",
  "number": "012-345-6789"
}

###

POST https://immense-brushlands-16614.herokuapp.com/api/persons/
Content-Type: application/json

{
  "name": "",
  "number": "012-345-6789"
}

###

POST https://immense-brushlands-16614.herokuapp.com/api/persons/
Content-Type: application/json

{
  "name": "Jane",
  "number": ""
}