PUT http://localhost:3003/api/blogs/60b9072e7c0d889b92659f28
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwYjhmZWY1N2IwYTM2OGQ5OGMzZjg0MCIsImlhdCI6MTYyMjc0MjM5OSwiZXhwIjoxNjIyNzQ1OTk5fQ.ud6mgzbCHUBah3YSEbii323_uutwRstQgR9p_zbrugY

{
  "likes": 10
}

###

PUT http://localhost:3003/api/blogs/60b9072e7c0d889b92659f28
Content-Type: application/json

{}